<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AuthService"
    targetNamespace="http://localhost:4000/soap/auth"
    xmlns:pns="http://localhost:4000/soap/auth"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

    <!-- <soap:Envelope
        xmlns:soap="http://schemas/xmlsoap.org/soap/envelope/"
        xmlns:pns="http://localhost:4000/soap/auth/">

        <soap:Header>
            <auth:AuthHeader xmlns:auth="http://localhost:4000/soap/auth/">
                <auth:token></auth:token>
            </auth:AuthHeader>
        </soap:Header>

        <soap:Body>
            <pns:SecuredListProducts/>
        </soap:Body>
    </soap:Envelope> -->

    <!-- Types de données -->
    <types>
        <xsd:schema targetNamespace="http://localhost:4000/soap/auth"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:complexType name="Auth">
                <xsd:sequence>
                    <xsd:element name="id" type="xsd:int"/>
                    <xsd:element name="email" type="xsd:string"/>
                    <xsd:element name="passwordHash" type="xsd:string"/>
                    <xsd:element name="role" type="xsd:Role"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>

    <!-- Messages -->
    <message name="LoginRequest">
        <part name="email" type="xsd:string"/>
        <part name="password" type="xsd:string"/>
    </message>
    <message name="LoginResponse">
        <part name="token" type="xsd:string"/>
    </message>

    <!-- Liste des opérations disponibles -->
    <portType name="AuthServicePort">
        <operation name="Login">
            <input message="pns:LoginRequest"/>
            <output message="pns:LoginRequest"/>
            <fault name="AuthFault" message="pns:AuthFault"/>
        </operation>
    </portType>

    <!-- Liaison SOAP -->
    <binding name="AuthServiceBinding" type="pns:AuthServicePort">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Login">
            <soap:operation soapAction="Login"/>
            <input>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/auth"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/auth"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <!-- Service SOAP -->
    <service name="AuthService">
        <port name="AuthServicePort" binding="pns:AuthServiceBinding">
            <soap:address location="http://localhost:4000/ws/"/>
        </port>
    </service>
</definitions>