<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ProductsService"
    targetNamespace="http://localhost:4000/soap/products"
    xmlns:pns="http://localhost:4000/soap/products"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

    <!-- Types de données -->
    <types>
        <xsd:schema targetNamespace="http://localhost:4000/soap/products"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:complexType name="Product">
                <xsd:sequence>
                    <xsd:element name="id" type="xsd:int"/>
                    <xsd:element name="title" type="xsd:string"/>
                    <xsd:element name="category" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="ean" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="description" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="specs" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="price" type="xsd:float"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>

    <!-- Messages -->
    <message name="ListProductsRequest"/>
    <message name="ListProductsResponse">
        <part name="products" type="pns:Product"/>
    </message>

    <message name="GetProductRequest"/>
    <message name="GetProductResponse">
        <part name="products" type="pns:Product"/>
    </message>

    <message name="DeleteProductRequest"/>
    <message name="DeleteProductResponse">
        <part name="products" type="pns:Product"/>
    </message>

    <message name="AddProductRequest"/>
    <message name="AddProductResponse">
        <part name="products" type="pns:Product"/>
    </message>

    <!-- Liste des opérations disponibles -->
    <portType name="ProductsServicePort">
        <operation name="ListProducts">
            <input message="pns:ListProductsRequest"/>
            <output message="pns:ListProductsResponse"/>
        </operation>
    </portType>

    <portType name="ProductsServicePort">
        <operation name="GetProduct">
            <input message="pns:GetProductRequest"/>
            <output message="pns:GetProductResponse"/>
        </operation>
    </portType>

    <portType name="ProductsServicePort">
        <operation name="DeleteProduct">
            <input message="pns:DeleteProductRequest"/>
            <output message="pns:DeleteProductResponse"/>
        </operation>
    </portType>

    <portType name="ProductsServicePort">
        <operation name="AddProduct">
            <input message="pns:AddProductRequest"/>
            <output message="pns:AddProductResponse"/>
        </operation>
    </portType>

    <!-- Liaison SOAP -->
    <binding name="ProductsServiceBinding" type="pns:ProductsServicePort">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ListProducts">
            <soap:operation soapAction="ListProducts"/>
            <input>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/products"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/products"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <binding name="ProductsServiceBinding" type="pns:ProductsServicePort">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetProduct">
            <soap:operation soapAction="GetProduct"/>
            <input>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/products"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/products"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <binding name="ProductsServiceBinding" type="pns:ProductsServicePort">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="DeleteProduct">
            <soap:operation soapAction="DeleteProduct"/>
            <input>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/products"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/products"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <binding name="ProductsServiceBinding" type="pns:ProductsServicePort">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="AddProduct">
            <soap:operation soapAction="AddProduct"/>
            <input>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/products"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="encoded"
                            namespace="http://localhost:4000/soap/products"
                            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <!-- Service SOAP -->
    <service name="ProductsService">
        <port name="ProductsServicePort" binding="pns:ProductsServiceBinding">
            <soap:address location="http://localhost:4000/ws/"/>
        </port>
    </service>
</definitions>